# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

# Coverage configuration
coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%  # 전체 프로젝트 커버리지 목표
        threshold: 1%  # 허용 가능한 커버리지 감소율
        base: auto
        if_ci_failed: error
    patch:
      default:
        target: 80%  # 새로운 코드의 커버리지 목표
        threshold: 1%
        base: auto

# PR 댓글 설정
comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true

# 무시할 파일/폴더 패턴
ignore:
  - "dist/**/*"
  - "coverage/**/*"
  - "config/**/*"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/tests/**/*"
  - "**/node_modules/**/*"
  - "**/*.config.js"
  - "**/*.config.ts"

# 플래그 설정 (선택사항 - 여러 테스트 스위트가 있을 경우)
flags:
  unit:
    paths:
      - src/
    carryforward: true

# GitHub Checks 설정
github_checks:
  annotations: true