version: '3.8'

services:
  theburgers:
    image: kbh1933/theburgers:latest
    container_name: theburgers
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Discord Configuration
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_ALERT_CHANNEL_ID=${DISCORD_ALERT_CHANNEL_ID}
      - DISCORD_BAN_CHANNEL_ID=${DISCORD_BAN_CHANNEL_ID}
      # CHZZK Configuration
      - NID_AUTH=${NID_AUTH}
      - NID_SESSION=${NID_SESSION}
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      # Web Server Configuration
      - WEB_PORT=${WEB_PORT:-3000}
      - ENABLE_WEB_SERVER=${ENABLE_WEB_SERVER:-true}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
      - NODE_ENV=${NODE_ENV:-production}

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
    command: --interval 300 --include-restarting
