name: Merge Staging to Main

on:
  workflow_run:
    workflows: Run Tests
    types:
      - completed

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge staging into main
        run: |
          git fetch origin main
          git checkout main
          git merge --ff-only origin/staging
          git push origin main
